### ISSUE TITLE
Discourage plain text pw in README

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [thematrixdev/home-assistant-clp#10]
## Problem
Using plain text PW in configuration file is not a good practice. It might be leaked easily if users share their configs for help.

## Solution
Suggest the use of [secrets](https://www.home-assistant.io/docs/configuration/secrets/) instead.

## Example:

```yaml
# configuration.yaml
sensor: 
  - platform: clp
    username: !secret clp_username
    password: !secret clp_pw
    type: 'HOURLY'
```

```yaml
# secrets.yaml
clp_username: "YOUR_USERNAME"
clp_pw: "YOUR_VERY_SECURE_PASSWORD"
```
