### ISSUE TITLE
 {"message":"Invalid handler specified" when choose intergation in HA

### ISSUE THREAD

**Issue by tastyrepublic** [thematrixdev/home-assistant-clp#4]
{"message":"Invalid handler specified" when choose intergation in HA

**Comment by thematrixdev** [comment]
> {"message":"Invalid handler specified" when choose intergation in HA

Could you provide any screenshots?

**Comment by tastyrepublic** [comment]
I don't need to choose it from the HA intergation right? I just find the entitles call CLP already, it show power useage hourly.
so its working I think.

**Comment by tastyrepublic** [comment]
Another question, what if I have multi location in 1 account? And thank you for making this intergation, I trying to use it for HA power grid to check the power usage, hope its work.

**Comment by thematrixdev** [comment]
> Another question, what if I have multi location in 1 account? And thank you for making this intergation, I trying to use it for HA power grid to check the power usage, hope its work.

Try using a different name:
```
sensor:
  - platform: clp
    name: 'CLP Location A' # whatever name you like
    username: '' # CLP web site username
    password: '' # CLP web site password
    timeout: 30 # connection timeout in second
    type: '' # type of data to be shown in state
  - platform: clp
    name: 'CLP Location B' # whatever name you like
    username: '' # CLP web site username
    password: '' # CLP web site password
    timeout: 30 # connection timeout in second
    type: '' # type of data to be shown in state
```
